const logos = () => { 
	return `       
-ツ▲ LOGOS PREMIUM ▲ツ-
❗ESSES PODEM NÃO FUNCIONAR POR SER SERVIDOR❗
♢➤ *${prefix}3dcube* (nome /nick)
♢➤ *${prefix}papel* (nome /nick)
♢➤ *${prefix}cup* (nome /nick)
♢➤ *${prefix}florest* (nome /nick)
♢➤ *${prefix}summer* (nome /nick)
♢➤ *${prefix}path* (nome /nick)
♢➤ *${prefix}fogos* (nome /nick)
♢➤ *${prefix}lighttxt* (nome /nick)
♢➤ *${prefix}flower* (nome /nick)
♢➤ *${prefix}textmar* (nome /nick)
♢➤ *${prefix}pornhub* (nome /nick)
♢➤ *${prefix}jokerlogo* (nome /nick)
♢➤ *${prefix}lavatext* (nome /nick)
♢➤ *${prefix}magma* (nome /nick)
♢➤ *${prefix}matrix* (nome /nick)
♢➤ *${prefix}breakwall* (nome /nick)
♢➤ *${prefix}nulis* (nome /nick)
♢➤ *${prefix}halloween* (nome /nick)
♢➤ *${prefix}breakwall* (nome /nick)

♢➤ *${prefix}greenhorror* (nome /nick)
♢➤ *${prefix}sciencefiction* (nome /nick)
♢➤ *${prefix}transformer* (nome /nick)
♢➤ *${prefix}berry* (nome /nick)
♢➤ *${prefix}magmahot* (nome /nick)
♢➤ *${prefix}3dstone* (nome /nick)
♢➤ *${prefix}3dneonlight* (nome /nick)
♢➤ *${prefix}impressiveglitch* (nome /nick)
♢➤ *${prefix}harrypotter* (nome /nick)
♢➤ *${prefix}embossed* (nome /nick)
♢➤ *${prefix}brokenglass* (nome /nick)
♢➤ *${prefix}artpaper* (nome /nick)
♢➤ *${prefix}3dglossy* (nome /nick)
♢➤ *${prefix}neondevilwings* (nome /nick)
♢➤ *${prefix}3dunderwater* (nome /nick)
♢➤ *${prefix}bearmascot* (nome /nick)
♢➤ *${prefix}wonderfulgraffiti* (nome /nick)
♢➤ *${prefix}futuristicneon* (nome /nick)
♢➤ *${prefix}snow* (nome /nick)
♢➤ *${prefix}cloud* (nome /nick)
♢➤ *${prefix}luxurygold* (nome /nick)
♢➤ *${prefix}realisticcloud* (nome /nick)
♢➤ *${prefix}sandsummer* (nome /nick)
♢➤ *${prefix}sandwriting* (nome /nick)
♢➤ *${prefix}sandengraved* (nome /nick)
♢➤ *${prefix}summerysand* (nome /nick)
♢➤ *${prefix}3dglue* (nome /nick)
♢➤ *${prefix}metaldarkgold* (nome /nick)
♢➤ *${prefix}neonlight* (nome /nick)
♢➤ *${prefix}3dgradient* (nome /nick)

♢➤ *${prefix}1917* (nome /nick)
♢➤ *${prefix}xmascards3d* (nome /nick)
♢➤ *${prefix}blood* (nome /nick)
♢➤ *${prefix}halloweenfire* (nome /nick)
♢➤ *${prefix}lava* (nome /nick)
♢➤ *${prefix}captainamerica* (nome /nick)
♢➤ *${prefix}steeltext* (nome /nick)
♢➤ *${prefix}toxic* (nome /nick)
♢➤ *${prefix}chocolate* (nome /nick)
♢➤ *${prefix}matrix* (nome /nick)
♢➤ *${prefix}horrorblood* (nome /nick)
♢➤ *${prefix}thunder2* (nome /nick)
♢➤ *${prefix}3dbox* (nome /nick)
♢➤ *${prefix}naturalleaves* (nome /nick)
♢➤ *${prefix}blackpink* (nome /nick)
♢➤ *${prefix}dropwater* (nome /nick)
♢➤ *${prefix}christmas* (nome /nick)
`
}
exports.logos = logos    